[build]
builder = "dockerfile"

[deploy]
startCommand = "apache2-foreground"
restartPolicyType = "always"

# WebSocket service configuration
[[services]]
name = "websocket-server"
startCommand = "php websocket_server.php $PORT"

[variables]
PORT = "8080"
WEBSOCKET_PORT = "8081"